export default {
  focus: {
    type: 'FocusEvent',
    validElements: [
      'TextInput',
      'Touchable',
      'TouchableBounce',
      'TouchableHighlight',
      'TouchableOpacity',
      'TouchableWithoutFeedback',
      'TouchableNativeFeedback',
    ],
  },
  blur: {
    type: 'BlurEvent',
    validElements: [
      'TextInput',
      'Touchable',
      'TouchableBounce',
      'TouchableHighlight',
      'TouchableOpacity',
      'TouchableWithoutFeedback',
    ],
  },
  change: {
    type: 'ChangeEvent',
    validElements: [
      'SegmentedControlIOS',
      'PickerIOS',
      'Switch',
      'DatePickerIOS',
      'Checkbox',
      'TextInput',
    ],
  },
  contentSizeChange: {
    type: 'ContentSizeChangeEvent',
    validElements: ['VirtualizedList', 'FlatList', 'SectionList', 'TextInput', 'ScrollView'],
  },
  endEditing: {
    type: 'EditingEvent',
    validElements: ['TextInput'],
  },
  keyPress: {
    type: 'KeyPressEvent',
    validElements: ['TextInput'],
  },
  submitEditing: {
    type: 'EditingEvent',
    validElements: ['TextInput'],
  },
  layout: {
    type: 'LayoutEvent',
    validElements: [
      'ActivityIndicator',
      'FlatList',
      'Image',
      'KeyboardAvoidingView',
      'ScrollView',
      'ScrollViewStickyHeader',
      'SectionList',
      'Text',
      'TextInput',
      'Touchable',
      'TouchableHighlight',
      'TouchableNativeFeedback',
      'TouchableOpacity',
      'TouchableWithoutFeedback',
      'View',
      'VirtualizedList',
      'WindowedListView',
    ],
  },
  selectionChange: {
    type: 'SelectionChangeEvent',
    validElements: ['TextInput'],
  },
  longPress: {
    type: 'PressEvent',
    validElements: [
      'Touchable',
      'TouchableBounce',
      'TouchableHighlight',
      'TouchableOpacity',
      'TouchableWithoutFeedback',
      'TouchableNativeFeedback',
    ],
  },
  press: {
    type: 'PressEvent',
    validElements: [
      'Button',
      'Touchable',
      'TouchableBounce',
      'TouchableHighlight',
      'TouchableOpacity',
      'TouchableWithoutFeedback',
      'TouchableNativeFeedback',
    ],
  },
  pressIn: {
    type: 'PressEvent',
    validElements: [
      'Touchable',
      'TouchableBounce',
      'TouchableHighlight',
      'TouchableOpacity',
      'TouchableWithoutFeedback',
      'TouchableNativeFeedback',
      'YellowBoxPressable',
    ],
  },
  pressOut: {
    type: 'PressEvent',
    validElements: [
      'Touchable',
      'TouchableBounce',
      'TouchableHighlight',
      'TouchableOpacity',
      'TouchableWithoutFeedback',
      'TouchableNativeFeedback',
      'YellowBoxPressable',
    ],
  },
  momentumScrollBegin: {
    type: 'ScrollEvent',
    validElements: [
      'ScrollResponder',
      'FlatList',
      'ScrollView',
      'SectionList',
      'VirtualizedList',
      'WindowedListView',
    ],
  },
  momentumScrollEnd: {
    type: 'ScrollEvent',
    validElements: [
      'ScrollResponder',
      'FlatList',
      'ScrollView',
      'SectionList',
      'VirtualizedList',
      'WindowedListView',
    ],
  },
  scroll: {
    type: 'ScrollEvent',
    validElements: [
      'ScrollResponder',
      'FlatList',
      'ScrollView',
      'SectionList',
      'TextInput',
      'VirtualizedList',
      'WindowedListView',
    ],
  },
  scrollBeginDrag: {
    type: 'ScrollEvent',
    validElements: [
      'ScrollResponder',
      'FlatList',
      'ScrollView',
      'SectionList',
      'VirtualizedList',
      'WindowedListView',
    ],
  },
  scrollEndDrag: {
    type: 'ScrollEvent',
    validElements: [
      'ScrollResponder',
      'FlatList',
      'ScrollView',
      'SectionList',
      'VirtualizedList',
      'WindowedListView',
    ],
  },
  load: {
    type: 'ImageLoadEvent',
    validElements: ['Image'],
  },
  error: {
    type: 'SyntheticEvent',
    validElements: ['Image'],
  },
  progress: {
    type: 'SyntheticEvent',
    validElements: ['Image'],
  },
};
